### PR TITLE
Upstreaming v3 gh3

### PR DESCRIPTION
**Pull request by TheNetAdmin**
This PR fixes several grammar nits found in `upstreaming-v3-gh2` PR.

### CODE REVIEW

**Comment by marc-orr** [comment]
I did a quick code review over all the patches and they all look good to me. I've also run the `amd_sev` test on a SEV-ES capable machine and all test cases worked.

**Comment by marc-orr** [comment]
FYI, Andrew Jones started leaving comments and then write an email asking you to resend the patched if you'd like to continue working on them so that the google email address doesn't bounce any more. Not sure if we want to address his latest comments before sending out v3, or after.

**Comment by TheNetAdmin** [comment]
Thank you for the timely notice! I also have set up a Gmail filter to capture our patchset's review email and keep them in the inbox.

I just read Andrew's comments. I think some of them require a few more days to develop. I already have a V3 with cover letter ready to send. In this case, maybe we can send our current V3 today or tomorrow, and apply Andrew's comments in V4?

**Comment by marc-orr** [comment]
> Thank you for the timely notice! I also have set up a Gmail filter to capture our patchset's review email and keep them in the inbox.
> 
> I just read Andrew's comments. I think some of them require a few more days to develop. I already have a V3 with cover letter ready to send. In this case, maybe we can send our current V3 today or tomorrow, and apply Andrew's comments in V4?

Yeah, I think that's a good plan. Because that's basically what Andrew requested us to do. We (probably you) can reply to Andrew's email that the v3 incorporates feedback up to last week, and we will work on a v4 to incorporate the new feedback.

**Comment by TheNetAdmin** [comment]
> 
> 
> > Thank you for the timely notice! I also have set up a Gmail filter to capture our patchset's review email and keep them in the inbox.
> > I just read Andrew's comments. I think some of them require a few more days to develop. I already have a V3 with cover letter ready to send. In this case, maybe we can send our current V3 today or tomorrow, and apply Andrew's comments in V4?
> 
> Yeah, I think that's a good plan. Because that's basically what Andrew requested us to do. We (probably you) can reply to Andrew's email that the v3 incorporates feedback up to last week, and we will work on a v4 to incorporate the new feedback.

Got it, I will reply to that email, then prepare and send the v3.

May I send an off-list v3 patch set to you before sending it to the mailing list,  so we can double-check it looks good? It's the first time I'm setting up the git send-email on my workstation so I want to make sure this initial setup is good enough.

**Comment by marc-orr** [comment]
> > > Thank you for the timely notice! I also have set up a Gmail filter to capture our patchset's review email and keep them in the inbox.
> > > I just read Andrew's comments. I think some of them require a few more days to develop. I already have a V3 with cover letter ready to send. In this case, maybe we can send our current V3 today or tomorrow, and apply Andrew's comments in V4?
> > 
> > 
> > Yeah, I think that's a good plan. Because that's basically what Andrew requested us to do. We (probably you) can reply to Andrew's email that the v3 incorporates feedback up to last week, and we will work on a v4 to incorporate the new feedback.
> 
> Got it, I will reply to that email, then prepare and send the v3.
> 
> May I send an off-list v3 patch set to you before sending it to the mailing list, so we can double-check it looks good? It's the first time I'm setting up the git send-email on my workstation so I want to make sure this initial setup is good enough.

Yes. I was actually going to suggest to send off-list before sending onlist. Don't forget to add the flags to suppress sending them to people tagged in the patches (e.g., Varad who is tagged as `Co-developed-by` and Andrew who is tagged with `Reviewed-by`).

**Pull request merged**
