### PR TITLE
Upstreaming uefi v1 gh2

### PR DESCRIPTION
**Pull request by TheNetAdmin**
Fixed the commit author and one exit code issues

### CODE REVIEW

**Comment by marc-orr** [comment]
This looks great! Tests results are good too. I think we can send this out to the list (finally :-)!).

By the way, I got confused on my last pass when I mentioned that the edits to the configure script should be in a separate commit authored by Paolo. I missed that he had already added the changes into a commit that was already committed. Sorry for the confusion.

Can we add my patch to make the `run_tests.sh` script (mostly) work to this series? If you don't mind, I can update the commit message and add it to this branch, and you can include it in the `git send-email`. Let me know if that's OK. Thanks!

**Comment by TheNetAdmin** [comment]
> Can we add my patch to make the `run_tests.sh` script (mostly) work to this series? If you don't mind, I can update the commit message and add it to this branch, and you can include it in the `git send-email`. Let me know if that's OK. Thanks!

That would be great! I can draft the cover letter and send it out later this week, probably Friday or the weekend.

**Comment by marc-orr** [comment]
Can you double check a [pull request](https://github.com/marc-orr/KVM-Unit-Tests-dev-fork/pull/11/commits/7388fb5120703497625a0793b4ce5ba9de5120aa) I just created to add my patch to make `run_tests.sh` mostly work to this branch so you can include it in your next upstream mail? If it looks good, I'll go ahead with the pull request so that you can use this branch to send the patches out. Thanks!

**Comment by TheNetAdmin** [comment]
> Can you double check a [pull request](https://github.com/marc-orr/KVM-Unit-Tests-dev-fork/pull/11/commits/7388fb5120703497625a0793b4ce5ba9de5120aa) I just created to add my patch to make `run_tests.sh` mostly work to this branch so you can include it in your next upstream mail? If it looks good, I'll go ahead with the pull request so that you can use this branch to send the patches out. Thanks!

Got it! I just quickly glanced through the pr and will pull and test it tomorrow (probably afternoon). If all goes well, I can make the patch set tomorrow afternoon or the weekend.

**Comment by marc-orr** [comment]
> > Can you double check a [pull request](https://github.com/marc-orr/KVM-Unit-Tests-dev-fork/pull/11/commits/7388fb5120703497625a0793b4ce5ba9de5120aa) I just created to add my patch to make `run_tests.sh` mostly work to this branch so you can include it in your next upstream mail? If it looks good, I'll go ahead with the pull request so that you can use this branch to send the patches out. Thanks!
> 
> Got it! I just quickly glanced through the pr and will pull and test it tomorrow (probably afternoon). If all goes well, I can make the patch set tomorrow afternoon or the weekend.

Sounds great! Please let me know if you need anything. Thanks!

**Pull request merged**
