### PR TITLE
Upstreaming v4 gh3

### PR DESCRIPTION
**Pull request by TheNetAdmin**
This version deletes the `x86/amd_sev.c` test case, as discussed in the mailing list.

### CODE REVIEW

**Comment by marc-orr** [comment]
Should we add a patch to add some of the test cases (e.g., at least MSR test case) as SEV? Or maybe I can test and then propose such a patch to be added to the series? What do you think?

**Comment by TheNetAdmin** [comment]
Hi Marc,

I can prepare a script for you to run all test cases under SEV and SEV-ES. Maybe tomorrow or later this week.

One thing I'm not sure about is: are we marking all test cases that run successfully under SEV, or are we only marking the relevant ones (the ones that test MSR or other SEV/SEV-ES protected resources like page table)?

I guess all test cases will run fine under SEV. If that's the case, I guess we are marking all of them?

**Comment by marc-orr** [comment]
I don't think you need to write a new script. They already have a script.
Maybe the right thing to do here is to mark all the test cases that run
under uefi as being in a new 'efi' group? Then, presumably, they all also
work under SEV and SEV-ES? I'm replying from my phone. I'll test it when
I'm back at my computer.

**Comment by TheNetAdmin** [comment]
There is a script to run all test cases under SeaBIOS, but that one is not compatible with EFI for now. I'll see what I can do in the following days.

I already have a Google sheets listing all test cases that can run under UEFI, I can generate the same list on my local workstation.

**Comment by marc-orr** [comment]
> There is a script to run all test cases under SeaBIOS, but that one is not compatible with EFI for now. I'll see what I can do in the following days.
> 
> I already have a Google sheets listing all test cases that can run under UEFI, I can generate the same list on my local workstation.

Ack. I will take a look this morning. We can also send the patch set without updating the .cfg file. Also, you got one more comment from Paolo this morning.

**Comment by marc-orr** [comment]
Well, looks like Paolo did send us a couple of patches based on his comment. (Which is great!) Also, I've been hacking on run_tests.sh (at the top of the KVM-Unit-Tests repo), and I sort of have it working to run the .efi test cases. In hindsight, we should've suggested to make this work with the EFI test cases from the start. Oops. Anyway, let me see if I can finish getting it working properly, and then I'll send you the patch. In other words, I guess we can wait another day or two to send out the v4.

**Comment by TheNetAdmin** [comment]
Got it, I will check out Paolo's patches and update our v4 patchset.

Actually, I planned to modify the `run_tests.sh` script in the future patchset LOL. Please note that the `-append` option does not work with the current EFI runner script because:

1. EFI test cases do not have the argument passing setup
2. EFI runner script does not use the `-kernel` argument for QEMU; providing a `-append` without `-kernel` will cause QEMU to report an error

**Comment by marc-orr** [comment]
> Got it, I will check out Paolo's patches and update our v4 patchset.
> 
> Actually, I planned to modify the `run_tests.sh` script in the future patchset LOL. Please note that the `-append` option does not work with the current EFI runner script because:
> 
> 1. EFI test cases do not have the argument passing setup
> 2. EFI runner script does not use the `-kernel` argument for QEMU; providing a `-append` without `-kernel` will cause QEMU to report an error

Got it now. So should I pause my effort getting `run_tests.sh` to work for now then? What do you prefer? I'm OK either way. I can finish what I started, and make it so that `run_tests.sh` works, and then we can touch base on how to resolve the argument passing issue. Or we can just send the current patch set out as is, without support for `run_test.sh`. Which do you prefer?

Apologies, I didn't mean to make things so complicated :-).

**Comment by TheNetAdmin** [comment]
> Got it now. So should I pause my effort getting `run_tests.sh` to work for now then? What do you prefer? I'm OK either way. I can finish what I started, and make it so that `run_tests.sh` works, and then we can touch base on how to resolve the argument passing issue. Or we can just send the current patch set out as is, without support for `run_test.sh`. Which do you prefer?
> 
> Apologies, I didn't mean to make things so complicated :-).

Ah sorry, my previous comment was a bit confusing :-). It's great that you can work on this, actually, I don't have much time until the weekend so I'm super happy that you are already working on it. We can make a new commit in the V4 patchset to include the `run_tests.sh` script, that would be very helpful.

**Comment by TheNetAdmin** [comment]
I was talking about `-append` so that you don't have to debug that part

**Comment by marc-orr** [comment]
Got it now! I'll continue my effort then. Thanks!

**Comment by marc-orr** [comment]
FYI, I got distracted yesterday and didn't finish my effort to get `run_test.sh` working. Paolo sent another review and said it needs to work and offered the start of a patch on how to do that. So I'll pick up from the patch he offered and hope to send you a working patch today.

**Comment by marc-orr** [comment]
FYI, Paolo merged the v3 into a `uefi` branch in the gitlab repo. This is good, but it means more work for us to post the v4 changes, because he'd like us to post them as incremental changes on top of v3, instead of a new patchset.

Maybe we can do another meeting to discuss next steps. If we want to keep using this github to collaborate locally before posting on the mailing list, I need to setup a new branch to reflect this new world :-).

**Comment by TheNetAdmin** [comment]
> FYI, Paolo merged the v3 into a `uefi` branch in the gitlab repo. This is good, but it means more work for us to post the v4 changes, because he'd like us to post them as incremental changes on top of v3, instead of a new patchset.
> 
> Maybe we can do another meeting to discuss next steps. If we want to keep using this github to collaborate locally before posting on the mailing list, I need to setup a new branch to reflect this new world :-).

I just saw the `uefi` branch on GitLab, and Paolo already built a new patch to report whether SEV-ES is enabled in the `x86/amd_sev.c` test case. It's great to see the patchset moving forward :-)

I agree we should make another meeting, I'm free this Friday after 12pm, or anytime this weekend/next Monday.

**Comment by marc-orr** [comment]
> > FYI, Paolo merged the v3 into a `uefi` branch in the gitlab repo. This is good, but it means more work for us to post the v4 changes, because he'd like us to post them as incremental changes on top of v3, instead of a new patchset.
> > Maybe we can do another meeting to discuss next steps. If we want to keep using this github to collaborate locally before posting on the mailing list, I need to setup a new branch to reflect this new world :-).
> 
> I just saw the `uefi` branch on GitLab, and Paolo already built a new patch to report whether SEV-ES is enabled in the `x86/amd_sev.c` test case. It's great to see the patchset moving forward :-)
> 
> I agree we should make another meeting, I'm free this Friday after 12pm, or anytime this weekend/next Monday.

Cool. I just sent an invite for tomorrow at 4:30.

By the way, I'm still working on getting run_tests.sh to work. I've been stuck on a bug all day, but I think I'm finally narrowing in on the cause (not sure yet). So hopefully I'll have something to share with you very soon.

**Comment by TheNetAdmin** [comment]
I just saw the invitation, the time works for me.

If the bug is still causing some trouble, maybe we can discuss on our tomorrow meeting. I can help with the debugging.

**Comment by marc-orr** [comment]
> Got it, I will check out Paolo's patches and update our v4 patchset.
> 
> Actually, I planned to modify the `run_tests.sh` script in the future patchset LOL. Please note that the `-append` option does not work with the current EFI runner script because:
> 
> 1. EFI test cases do not have the argument passing setup
> 2. EFI runner script does not use the `-kernel` argument for QEMU; providing a `-append` without `-kernel` will cause QEMU to report an error

I got efi_tests.sh to run the test cases. But now I think I'm running into point #1 above: "EFI test cases do not have the argument passing setup". In particular, the KVM-Unit-Tests relies on propagating the test case's exit code as the QEMU return code. Or at least that's my understanding. And I have no idea how to get this part working :-). Maybe you've given it some thought?

Let me clean up my code and post the patches as a pull request on the dev branch, and we can discuss it tomorrow. Thanks!

**Comment by TheNetAdmin** [comment]
Ah I guess the return code problem is not quite related to the argument passing I mentioned. I think fixing the return code should be trivial, we can discuss this tomorrow.

**Comment by marc-orr** [comment]
Sounds good. Here's what I got working:
https://github.com/marc-orr/KVM-Unit-Tests-dev-fork/pull/8

As you'll see, I basically addressed none of the difficult points you mentioned... (-append, argument passing, return code). And this took way too much time to get working!

First patch is what Paolo proposed in his reviews.
2nd patch is my edits to get `run_tests.sh` to run all the test cases in `x86/unittests.cfg`

**Comment by marc-orr** [comment]
I've added the `uefi` branch into the repo: https://github.com/marc-orr/KVM-Unit-Tests-dev-fork/commits/uefi

**Pull request merged**
