### PR TITLE
Upstreaming v4 gh1

### PR DESCRIPTION
**Pull request by TheNetAdmin**
Hi Marc,

I just prepared a v4 draft patch set that applies all comments we have discussed.

I have only tested a few test cases. I will do a complete test and compare tomorrow and post the results here.

### CODE REVIEW

**Comment by TheNetAdmin** [comment]
All test cases:

```
Comparing               access: diff result: 0
Comparing              asyncpf: diff result: 0
Comparing                  cet: diff result: 0
Comparing                debug: diff result: 0
Comparing             emulator: diff result: 0
Comparing            hypercall: diff result: 0
Comparing         hyperv_clock: diff result: 1
Comparing   hyperv_connections: diff result: 0
Comparing        hyperv_stimer: diff result: 0
Comparing         hyperv_synic: diff result: 0
Comparing             idt_test: diff result: 0
Comparing                 init: diff result: 0
Comparing          intel-iommu: diff result: 1
Comparing               ioapic: diff result: 0
Comparing        kvmclock_test: diff result: 1
Comparing               memory: diff result: 0
Comparing                  msr: diff result: 0
Comparing                 pcid: diff result: 0
Comparing                  pks: diff result: 0
Comparing                  pku: diff result: 0
Comparing                  pmu: diff result: 1
Comparing              pmu_lbr: diff result: 0
Comparing                rdpru: diff result: 0
Comparing           rmap_chain: diff result: 1
Comparing                   s3: diff result: 1
Comparing               setjmp: diff result: 0
Comparing                sieve: diff result: 0
Comparing                 smap: diff result: 1
Comparing              smptest: diff result: 0
Comparing              syscall: diff result: 0
Comparing                  tsc: diff result: 1
Comparing           tsc_adjust: diff result: 1
Comparing             tsx-ctrl: diff result: 0
Comparing                 umip: diff result: 0
Comparing               vmexit: diff result: 1
Comparing     vmware_backdoors: diff result: 0
Comparing                xsave: diff result: 0
```

Output:
[upstreaming-v4-gh1-compare.zip](https://github.com/marc-orr/KVM-Unit-Tests-dev-fork/files/7350030/upstreaming-v4-gh1-compare.zip)

Just checked these output, and found them equivalent to our previous V3 testing output: https://github.com/marc-orr/KVM-Unit-Tests-dev-fork/pull/1#issuecomment-932671503

**Comment by marc-orr** [comment]
Code looks good. I left one nit and one comment to double check.

I'm going to run the SEV tests now. I'll report back shortly.

**Comment by marc-orr** [comment]
Ugh. The SEV test fails. It's unable to enter the test case. Any idea what might be wrong? I tested the v3 patches just to make sure my setup is good, and they work fine.

The tests hangs here:

```
I1016 15:44:05.430420   35700 tube_backend_log.cc:85] BIOS: SetUefiImageMemoryAttributes - 0x000000003E2E7000 - 0x0000000000008000 (0x0000000000000008)
I1016 15:44:05.430681   35700 tube_backend_log.cc:85] BIOS: SetUefiImageMemoryAttributes - 0x000000003E2E0000 - 0x0000000000007000 (0x0000000000000008)
I1016 15:44:05.430930   35700 tube_backend_log.cc:85] BIOS: SetUefiImageMemoryAttributes - 0x000000003E2D8000 - 0x0000000000008000 (0x0000000000000008)
I1016 15:44:05.431192   35700 tube_backend_log.cc:85] BIOS: SetUefiImageMemoryAttributes - 0x000000003E2B9000 - 0x000000000001F000 (0x0000000000000008)
I1016 15:44:05.431443   35700 tube_backend_log.cc:85] BIOS: SetUefiImageMemoryAttributes - 0x000000003E2B2000 - 0x0000000000007000 (0x0000000000000008)
I1016 15:44:05.431692   35700 tube_backend_log.cc:85] BIOS: SetUefiImageMemoryAttributes - 0x000000003E2AC000 - 0x0000000000006000 (0x0000000000000008)
I1016 15:44:05.431946   35700 tube_backend_log.cc:85] BIOS: SetUefiImageMemoryAttributes - 0x000000003E2A4000 - 0x0000000000008000 (0x0000000000000008)
I1016 15:44:05.432199   35700 tube_backend_log.cc:85] BIOS: SetUefiImageMemoryAttributes - 0x000000003E29F000 - 0x0000000000005000 (0x0000000000000008)
I1016 15:44:05.432449   35700 tube_backend_log.cc:85] BIOS: SetUefiImageMemoryAttributes - 0x000000003E298000 - 0x0000000000007000 (0x0000000000000008)
I1016 15:44:05.469089   35711 tube_backend_log.cc:85] kernel_ttyS0: BdsDxe: loading Boot0001 \"UEFI nvme0\" from PciRoot(0x0)/Pci(0x3,0x0)/NVMe(0x1,00-00-00-00-00-00-00-00)
I1016 15:44:05.469100   35711 tube_backend_log.cc:85] kernel_ttyS0: BdsDxe: starting Boot0001 \"UEFI nvme0\" from PciRoot(0x0)/Pci(0x3,0x0)/NVMe(0x1,00-00-00-00-00-00-00-00)
I1016 15:44:05.469102   35711 tube_backend_log.cc:85] kernel_ttyS0:
I1016 15:44:05.469104   35711 tube_backend_log.cc:85] kernel_ttyS0: UEFI: Attempting to start image.
I1016 15:44:05.469106   35711 tube_backend_log.cc:85] kernel_ttyS0: Description: UEFI nvme0
I1016 15:44:05.469108   35711 tube_backend_log.cc:85] kernel_ttyS0: FilePath: PciRoot(0x0)/Pci(0x3,0x0)/NVMe(0x1,00-00-00-00-00-00-00-00)
I1016 15:44:05.469110   35711 tube_backend_log.cc:85] kernel_ttyS0: OptionNumber: 1.
I1016 15:44:05.469112   35711 tube_backend_log.cc:85] kernel_ttyS0:
I1016 15:44:05.475135   35714 tube_backend_log.cc:85] CONSOLE: BdsDxe: loading Boot0001 \"UEFI nvme0\" from PciRoot(0x0)/Pci(0x3,0x0)/NVMe(0x1,00-00-00-00-00-00-00-00)
I1016 15:44:05.475144   35714 tube_backend_log.cc:85] CONSOLE: BdsDxe: starting Boot0001 \"UEFI nvme0\" from PciRoot(0x0)/Pci(0x3,0x0)/NVMe(0x1,00-00-00-00-00-00-00-00)
I1016 15:44:05.475146   35714 tube_backend_log.cc:85] CONSOLE:
I1016 15:44:05.475149   35714 tube_backend_log.cc:85] CONSOLE: UEFI: Attempting to start image.
I1016 15:44:05.475150   35714 tube_backend_log.cc:85] CONSOLE: Description: UEFI nvme0
I1016 15:44:05.475152   35714 tube_backend_log.cc:85] CONSOLE: FilePath: PciRoot(0x0)/Pci(0x3,0x0)/NVMe(0x1,00-00-00-00-00-00-00-00)
I1016 15:44:05.475154   35714 tube_backend_log.cc:85] CONSOLE: OptionNumber: 1.
I1016 15:44:05.475155   35714 tube_backend_log.cc:85] CONSOLE:
```

**Comment by TheNetAdmin** [comment]
Emm let me double-check the SEV code... I guess it's related to the setup refactoring.

**Comment by TheNetAdmin** [comment]
I have a guess, how about in v4, reorganize this set up code

https://github.com/marc-orr/KVM-Unit-Tests-dev-fork/blob/1470192d3f592a03df5132fef8f435edcded5189/lib/x86/setup.c#L295-L355

to

```C
efi_status_t setup_efi(efi_bootinfo_t *efi_bootinfo)
{
	efi_status_t status;

	status = setup_memory_allocator(efi_bootinfo);
	if (status != EFI_SUCCESS) {
		printf("Failed to set up memory allocator: ");
		switch (status) {
		case EFI_OUT_OF_RESOURCES:
			printf("No free memory region\n");
			break;
		default:
			printf("Unknown error\n");
			break;
		}
		return status;
	}
	
	status = setup_rsdp(efi_bootinfo);
	if (status != EFI_SUCCESS) {
		printf("Cannot find RSDP in EFI system table\n");
		return status;
	}

	status = setup_amd_sev();
	if (status != EFI_SUCCESS) {
		switch (status) {
		case EFI_UNSUPPORTED:
			/* Continue if AMD SEV is not supported */
			break;
		default:
			printf("Set up AMD SEV failed\n");
			return status;
		}
	}

	status = setup_amd_sev_es();
	if (status != EFI_SUCCESS) {
		switch (status) {
		case EFI_UNSUPPORTED:
			/* Continue if AMD SEV-ES is not supported */
			break;
		default:
			printf("Set up AMD SEV-ES failed\n");
			return status;
		}
	}

	reset_apic();
	setup_gdt_tss();
	setup_idt();
	load_idt();
	mask_pic_interrupts();
	enable_apic();
	enable_x2apic();
	smp_init();
	setup_page_table();


	return EFI_SUCCESS;
}
```

I guess some setup process is in the wrong order. If this does not work, maybe we can find a time to quickly GVC and debug together?

**Comment by marc-orr** [comment]
Changing the order, as you proposed in your last comment works!

```
I1016 16:27:20.253391   48786 tube_backend_log.cc:85] kernel_ttyS0: BdsDxe: loading Boot0001 \"UEFI nvme0\" from PciRoot(0x0)/Pci(0x3,0x0)/NVMe(0x1,00-00-00-00-00-00-00-00)
I1016 16:27:20.253416   48786 tube_backend_log.cc:85] kernel_ttyS0: BdsDxe: starting Boot0001 \"UEFI nvme0\" from PciRoot(0x0)/Pci(0x3,0x0)/NVMe(0x1,00-00-00-00-00-00-00-00)
I1016 16:27:20.253418   48786 tube_backend_log.cc:85] kernel_ttyS0:
I1016 16:27:20.253421   48786 tube_backend_log.cc:85] kernel_ttyS0: UEFI: Attempting to start image.
I1016 16:27:20.253423   48786 tube_backend_log.cc:85] kernel_ttyS0: Description: UEFI nvme0
I1016 16:27:20.253425   48786 tube_backend_log.cc:85] kernel_ttyS0: FilePath: PciRoot(0x0)/Pci(0x3,0x0)/NVMe(0x1,00-00-00-00-00-00-00-00)
I1016 16:27:20.253427   48786 tube_backend_log.cc:85] kernel_ttyS0: OptionNumber: 1.
I1016 16:27:20.253429   48786 tube_backend_log.cc:85] kernel_ttyS0:
I1016 16:27:20.253430   48786 tube_backend_log.cc:85] kernel_ttyS0: enabling apic
I1016 16:27:20.253432   48786 tube_backend_log.cc:85] kernel_ttyS0: SEV activation test is loaded.
I1016 16:27:20.261109   48463 tube_backend_log.cc:85] kernel_ttyS0: CPUID Fn8000_0000[EAX]: 0x8000001f
I1016 16:27:20.261118   48463 tube_backend_log.cc:85] kernel_ttyS0: CPUID Fn8000_001F[EAX]: 0x00000002
I1016 16:27:20.261121   48463 tube_backend_log.cc:85] kernel_ttyS0: CPUID Fn8000_001F[EBX]: 0x0000002f
I1016 16:27:20.261124   48463 tube_backend_log.cc:85] kernel_ttyS0: SEV is supported
I1016 16:27:20.261127   48463 tube_backend_log.cc:85] kernel_ttyS0: MSR C001_0131[EAX]: 0x00000003
I1016 16:27:20.261129   48463 tube_backend_log.cc:85] kernel_ttyS0: SEV is enabled
I1016 16:27:20.261132   48463 tube_backend_log.cc:85] kernel_ttyS0: PASS: SEV activation test.
I1016 16:27:20.261134   48463 tube_backend_log.cc:85] kernel_ttyS0: PASS: SEV-ES activation test.
I1016 16:27:20.261137   48463 tube_backend_log.cc:85] kernel_ttyS0: PASS: SEV-ES MSR test.
I1016 16:27:20.261140   48463 tube_backend_log.cc:85] kernel_ttyS0: SUMMARY: 3 tests
```

**Comment by TheNetAdmin** [comment]
Aha that's great!

I will fold this ordering change to the next v4-gh2 version, together with two other comments in RSDP commit.

I will make this new pull request later tonight, and maybe send our V4 tomorrow if everything goes well.

**Comment by marc-orr** [comment]
> Aha that's great!
> 
> I will fold this ordering change to the next v4-gh2 version, together with two other comments in RSDP commit.
> 
> I will make this new pull request later tonight, and maybe send our V4 tomorrow if everything goes well.

Sounds perfect. Thanks, Zixuan!

**Comment by TheNetAdmin** [comment]
> Sounds perfect. Thanks, Zixuan!

No problem! And thank you for taking the time to review and test the code :-)!

**Pull request merged**
