### PR TITLE
Upstreaming v4 gh2

### PR DESCRIPTION
**Pull request by TheNetAdmin**
1. Fixed two nits in RSDP commit
2. Fixed the set up ordering to fix SEV issues in `upstreaming-v4-gh1` version

Test cases are running, will post results later once finished.

### CODE REVIEW

**Comment by marc-orr** [comment]
Code and SEV test cases are good. LGTM.

**Comment by TheNetAdmin** [comment]
Great! I just checked all test cases and they seem fine running under UEFI and SeaBIOS:

```
Comparing               access: diff result: 0
Comparing              asyncpf: diff result: 0
Comparing                  cet: diff result: 0
Comparing                debug: diff result: 0
Comparing             emulator: diff result: 0
Comparing            hypercall: diff result: 0
Comparing         hyperv_clock: diff result: 1
Comparing   hyperv_connections: diff result: 0
Comparing        hyperv_stimer: diff result: 0
Comparing         hyperv_synic: diff result: 0
Comparing             idt_test: diff result: 0
Comparing                 init: diff result: 0
Comparing          intel-iommu: diff result: 1
Comparing               ioapic: diff result: 0
Comparing        kvmclock_test: diff result: 1
Comparing               memory: diff result: 0
Comparing                  msr: diff result: 0
Comparing                 pcid: diff result: 0
Comparing                  pks: diff result: 0
Comparing                  pku: diff result: 0
Comparing                  pmu: diff result: 1
Comparing              pmu_lbr: diff result: 0
Comparing                rdpru: diff result: 0
Comparing           rmap_chain: diff result: 1
Comparing                   s3: diff result: 1
Comparing               setjmp: diff result: 0
Comparing                sieve: diff result: 0
Comparing                 smap: diff result: 1
Comparing              smptest: diff result: 0
Comparing              syscall: diff result: 0
Comparing                  tsc: diff result: 1
Comparing           tsc_adjust: diff result: 0
Comparing             tsx-ctrl: diff result: 0
Comparing                 umip: diff result: 0
Comparing               vmexit: diff result: 1
Comparing     vmware_backdoors: diff result: 0
Comparing                xsave: diff result: 0
```

[upstreaming-v4-gh2-compare.zip](https://github.com/marc-orr/KVM-Unit-Tests-dev-fork/files/7361840/upstreaming-v4-gh2-compare.zip)

I will post the patchset to the mailing list tomorrow.

**Comment by marc-orr** [comment]
Sounds great!

**Comment by TheNetAdmin** [comment]
Hi Marc,

I just got a review comment on the SEV-ES test case

https://lore.kernel.org/kvm/6a5a16f7-c350-a48d-c5e7-352455b57c09@suse.com/

I think the real problem is that the current SEV-ES test case is not meaningful. And this comment also applies to the SEV test case (introduced by PATCH v3 12/17)

I remember we discussed this before, and the conclusion was "it's good to have it for development, but may not need it for the final patchset".

So in this case, maybe we can remove these SEV test cases from our v4 patchset?

**Comment by marc-orr** [comment]
> Hi Marc,
> 
> I just got a review comment on the SEV-ES test case
> 
> https://lore.kernel.org/kvm/6a5a16f7-c350-a48d-c5e7-352455b57c09@suse.com/
> 
> I think the real problem is that the current SEV-ES test case is not meaningful. And this comment also applies to the SEV test case (introduced by PATCH v3 12/17)
> 
> I remember we discussed this before, and the conclusion was "it's good to have it for development, but may not need it for the final patchset".
> 
> So in this case, maybe we can remove these SEV test cases from our v4 patchset?

Ack. Sorry, I was offline yesterday. Removing seems fine. I wonder if we can somehow capture which tests are known to be good to run under SEV and/or SEV-ES though? There's a `groups` attribute in the x86/unittests.cfg file. The name `groups` implies a test can be tagged to be apart of more than one group. However, I don't see any examples of this. But maybe we can tag the msr test, and any others that are good to run under SEV as sev? I can add this comment to the mailing list as well.

**Pull request merged**
